language: generic

sudo: required

cache:
  directories:
    - $HOME/.stack

before_install:
  # Install latest version of stack
  - >-
    travis_retry
    curl --location https://www.stackage.org/stack/linux-x86_64
    | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  # Build dependencies
  - stack --no-terminal --install-ghc test --only-dependencies

script:
  - ./Documentation/Shakefile.hs

deploy:
  local-dir: docs
  provider: pages
  repo: feramhq/documentation
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
