name: feram-documentation
version: 0.1.0.0
github: feramhq/documentation
license: AllRightsReserved
author: Adrian Sieber
maintainer: adrian@feram.io
copyright: Feram GmbH

description: >-
  Please see the readme on GitHub at
  <https://github.com/feramhq/documentation>

dependencies:
  - aeson
  - aeson-pretty
  - base
  - clay
  - language-docker
  - shake
  - text

library:
  source-dirs: .
