name: feram-documentation
version: 0.1.0.0
github: feramhq/documentation
license: AllRightsReserved
author: Adrian Sieber
maintainer: adrian@feram.io
copyright: Feram GmbH

description: >-
  Please see the readme on GitHub at
  <https://github.com/feramhq/documentation>

language: GHC2021

default-extensions:
  - DeriveAnyClass
  - LambdaCase
  - MultiWayIf
  - OverloadedRecordDot
  - OverloadedStrings
  - RecordWildCards
  - TypeFamilies
  - UndecidableInstances

dependencies:
  - aeson
  - aeson-pretty
  - base
  - bytestring
  - clay
  - directory
  - extra
  - free
  - hashable
  - language-docker
  - monoid-subclasses
  - protolude
  - shake
  - text
  - unordered-containers

executables:
  fresh-haddock:
    main: Main.hs
    source-dirs: app
